"""add detected_title to documents

Revision ID: d79468cb3214
Revises: d5d75b10a1f5
Create Date: 2026-08-10 19:12:56.102872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd79468cb3214'
down_revision: Union[str, Sequence[str], None] = 'd5d75b10a1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('detected_title', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'detected_title')
    # ### end Alembic commands ###
